name: MacOS

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-macos
  cancel-in-progress: true

jobs:
  MacOS-Clang:
    name: Apple Clang@11.0
    runs-on: macos-latest
    # env: {CXXFLAGS: "-fno-operator-names -Werror -Wall -Wextra -Wpedantic -Wnull-dereference -Wfloat-conversion -Wshadow -Woverloaded-virtual"}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install Dependencies
      run: .github/workflows/dependencies/dependencies_mac.sh

    - name: Configure Project and Generate Build System
      run: |
        cmake \
          -B${{runner.workspace}}/ROMSX/build \
          -DBUILD_SHARED_LIBS:BOOL=TRUE \
          -DCMAKE_CXX_COMPILER_LAUNCHER=$(which ccache) \
          -DCMAKE_BUILD_TYPE:STRING=Debug \
          -DROMSX_DIM:STRING=3 \
          -DROMSX_ENABLE_MPI:BOOL=TRUE \
          -DROMSX_ENABLE_TESTS:BOOL=TRUE \
          -DROMSX_ENABLE_ALL_WARNINGS:BOOL=TRUE \
          -DROMSX_ENABLE_FCOMPARE:BOOL=TRUE \
          ${{github.workspace}};

    - name: Compile and Link
      run: |
        cmake --build ${{runner.workspace}}/ROMSX/build --parallel 2 --verbose

 #  - name: CMake Tests # see file ROMSX/Tests/CTestList.cmake
 #    run: |
 #      ctest
 #    working-directory: ${{runner.workspace}}/ROMSX/build
