name: Windows

on: [pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-windows
  cancel-in-progress: true

jobs:
  WIN32-MSVC10:
    name: WIN32 MSVC@19.29
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Configure Project and Generate Build System
      run: |
        cmake -S . -B build `
          -DCMAKE_INSTALL_PREFIX:PATH=${{runner.workspace}}/REMORA/install `
          -DCMAKE_BUILD_TYPE:STRING=Debug `
          -DREMORA_DIM:STRING=3 `
          -DREMORA_ENABLE_MPI:BOOL=OFF `
          -DREMORA_ENABLE_TESTS:BOOL=ON `
          -DREMORA_ENABLE_ALL_WARNINGS:BOOL=OFF `
          -DREMORA_ENABLE_FCOMPARE:BOOL=ON `
          ${{github.workspace}};

    - name: Compile and Link
      run: |
        cmake --build build --parallel 2 --verbose

    - name: CMake Tests # see file REMORA/Tests/CTestList.cmake
      run: |
        ctest -L regression -VV
      working-directory: ${{runner.workspace}}/REMORA/build
